name: C/C++ CI

on: 
  push:
    branches: 
      - master
jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: snickerbockers/cmake-configure@prerel1
    - name: cmake build
      run: cmake --build build

