name: C/C++ CI

on: 
  push:
    branches: 
      - master
jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Archlinux CMake builder
      uses: codehz/arch-cmake-builder@v0.1.3

